// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

function copyUser(value$comptime1) {
  return {
    name: value$comptime1.name,
    age: value$comptime1.age,
    active: value$comptime1.active
  };
}

function copyPair(value$comptime2) {
  return [
    value$comptime2[0],
    value$comptime2[1]
  ];
}

function copyColor(value$comptime3) {
  let match;
  switch (value$comptime3) {
    case "Red" :
      match = Primitive_option.some(undefined);
      break;
    case "Green" :
    case "Blue" :
      match = undefined;
      break;
  }
  if (match !== undefined) {
    return "Red";
  }
  let match$1;
  switch (value$comptime3) {
    case "Green" :
      match$1 = Primitive_option.some(undefined);
      break;
    case "Red" :
    case "Blue" :
      match$1 = undefined;
      break;
  }
  if (match$1 !== undefined) {
    return "Green";
  }
  let match$2;
  switch (value$comptime3) {
    case "Red" :
    case "Green" :
      match$2 = undefined;
      break;
    case "Blue" :
      match$2 = Primitive_option.some(undefined);
      break;
  }
  if (match$2 !== undefined) {
    return "Blue";
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function copyShape(value$comptime4) {
  let match;
  match = typeof value$comptime4 !== "object" ? Primitive_option.some(undefined) : undefined;
  if (match !== undefined) {
    return "Point";
  }
  let payload$comptime5;
  payload$comptime5 = typeof value$comptime4 !== "object" || value$comptime4.TAG !== "Circle" ? undefined : value$comptime4._0;
  if (payload$comptime5 !== undefined) {
    return {
      TAG: "Circle",
      _0: payload$comptime5
    };
  }
  let payload$comptime6;
  payload$comptime6 = typeof value$comptime4 !== "object" || value$comptime4.TAG === "Circle" ? undefined : [
      value$comptime4._0,
      value$comptime4._1
    ];
  if (payload$comptime6 !== undefined) {
    return {
      TAG: "Rect",
      _0: payload$comptime6[0],
      _1: payload$comptime6[1]
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function copyInts(value$comptime7) {
  return Stdlib_List.fromArray(Stdlib_List.toArray(value$comptime7).map(arg$comptime0 => arg$comptime0));
}

function copyResult(value$comptime8) {
  let payload$comptime9;
  payload$comptime9 = value$comptime8.TAG === "Ok" ? value$comptime8._0 : undefined;
  if (payload$comptime9 !== undefined) {
    return {
      TAG: "Ok",
      _0: payload$comptime9
    };
  }
  let payload$comptime10;
  payload$comptime10 = value$comptime8.TAG === "Ok" ? undefined : value$comptime8._0;
  if (payload$comptime10 !== undefined) {
    return {
      TAG: "Error",
      _0: payload$comptime10
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

let ada = {
  name: "Ada",
  age: 42,
  active: true
};

let agePair = [
  "Ada",
  42
];

let sampleShape = {
  TAG: "Rect",
  _0: 3,
  _1: 4
};

let numbers = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

let score = {
  TAG: "Ok",
  _0: 7
};

let copiedAda = copyUser(ada);

let copiedPair = copyPair(agePair);

let copiedColor = copyColor("Green");

let copiedShape = copyShape(sampleShape);

let copiedNumbers = copyInts(numbers);

let copiedScore = copyResult(score);

console.log(copiedAda);

console.log(copiedPair);

console.log(copiedColor);

console.log(copiedShape);

console.log(copiedNumbers);

console.log(copiedScore);

let favoriteColor = "Green";

export {
  copyUser,
  copyPair,
  copyColor,
  copyShape,
  copyInts,
  copyResult,
  ada,
  agePair,
  favoriteColor,
  sampleShape,
  numbers,
  score,
  copiedAda,
  copiedPair,
  copiedColor,
  copiedShape,
  copiedNumbers,
  copiedScore,
}
/* copiedAda Not a pure module */
