// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";

function decodeUser(json$comptime1) {
  if (typeof json$comptime1 !== "object" || json$comptime1 === null || Array.isArray(json$comptime1)) {
    return;
  }
  let valueJson$comptime3 = json$comptime1["name"];
  if (valueJson$comptime3 === undefined) {
    return;
  }
  let value$comptime5;
  value$comptime5 = typeof valueJson$comptime3 === "string" ? valueJson$comptime3 : undefined;
  if (value$comptime5 === undefined) {
    return;
  }
  let valueJson$comptime6 = json$comptime1["age"];
  if (valueJson$comptime6 === undefined) {
    return;
  }
  let value$comptime8;
  value$comptime8 = typeof valueJson$comptime6 === "number" ? valueJson$comptime6 | 0 : undefined;
  if (value$comptime8 === undefined) {
    return;
  }
  let valueJson$comptime9 = json$comptime1["active"];
  if (valueJson$comptime9 === undefined) {
    return;
  }
  let value$comptime11;
  value$comptime11 = typeof valueJson$comptime9 === "boolean" ? valueJson$comptime9 : undefined;
  if (value$comptime11 !== undefined) {
    return {
      name: value$comptime5,
      age: value$comptime8,
      active: value$comptime11
    };
  }
}

function decodePair(json$comptime12) {
  if (!Array.isArray(json$comptime12)) {
    return;
  }
  let valueJson$comptime14 = json$comptime12[0];
  if (valueJson$comptime14 === undefined) {
    return;
  }
  let value$comptime16;
  value$comptime16 = typeof valueJson$comptime14 === "string" ? valueJson$comptime14 : undefined;
  if (value$comptime16 === undefined) {
    return;
  }
  let valueJson$comptime17 = json$comptime12[1];
  if (valueJson$comptime17 === undefined) {
    return;
  }
  let value$comptime19;
  value$comptime19 = typeof valueJson$comptime17 === "number" ? valueJson$comptime17 | 0 : undefined;
  if (value$comptime19 !== undefined) {
    return [
      value$comptime16,
      value$comptime19
    ];
  }
}

function decodeColor(json$comptime20) {
  if (typeof json$comptime20 === "string") {
    if ("Red" === json$comptime20) {
      return "Red";
    } else if ("Green" === json$comptime20) {
      return "Green";
    } else if ("Blue" === json$comptime20) {
      return "Blue";
    } else {
      return;
    }
  }
}

function decodeShape(json$comptime24) {
  if (typeof json$comptime24 !== "object" || json$comptime24 === null || Array.isArray(json$comptime24)) {
    return;
  }
  let match = json$comptime24["tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if ("Point" === match) {
    return "Point";
  }
  if ("Circle" === match) {
    let valueJson$comptime28 = json$comptime24["value"];
    if (valueJson$comptime28 === undefined) {
      return;
    }
    let value$comptime30;
    value$comptime30 = typeof valueJson$comptime28 === "number" ? valueJson$comptime28 : undefined;
    if (value$comptime30 !== undefined) {
      return {
        TAG: "Circle",
        _0: value$comptime30
      };
    } else {
      return;
    }
  }
  if ("Rect" !== match) {
    return;
  }
  let valueJson$comptime31 = json$comptime24["value"];
  if (valueJson$comptime31 === undefined) {
    return;
  }
  let value$comptime39;
  if (Array.isArray(valueJson$comptime31)) {
    let valueJson$comptime33 = valueJson$comptime31[0];
    if (valueJson$comptime33 !== undefined) {
      let value$comptime35;
      value$comptime35 = typeof valueJson$comptime33 === "number" ? valueJson$comptime33 : undefined;
      if (value$comptime35 !== undefined) {
        let valueJson$comptime36 = valueJson$comptime31[1];
        if (valueJson$comptime36 !== undefined) {
          let value$comptime38;
          value$comptime38 = typeof valueJson$comptime36 === "number" ? valueJson$comptime36 : undefined;
          value$comptime39 = value$comptime38 !== undefined ? [
              value$comptime35,
              value$comptime38
            ] : undefined;
        } else {
          value$comptime39 = undefined;
        }
      } else {
        value$comptime39 = undefined;
      }
    } else {
      value$comptime39 = undefined;
    }
  } else {
    value$comptime39 = undefined;
  }
  if (value$comptime39 !== undefined) {
    return {
      TAG: "Rect",
      _0: value$comptime39[0],
      _1: value$comptime39[1]
    };
  }
}

function decodeInts(json$comptime40) {
  if (Array.isArray(json$comptime40)) {
    return Stdlib_Array.reduceRight(json$comptime40, /* [] */0, (arg$comptime0, arg$comptime1) => {
      let match;
      match = typeof arg$comptime1 === "number" ? arg$comptime1 | 0 : undefined;
      if (match !== undefined && arg$comptime0 !== undefined) {
        return {
          hd: match,
          tl: arg$comptime0
        };
      }
    });
  }
}

function decodeResult(json$comptime45) {
  if (typeof json$comptime45 !== "object" || json$comptime45 === null || Array.isArray(json$comptime45)) {
    return;
  }
  let match = json$comptime45["tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if ("Ok" === match) {
    let valueJson$comptime49 = json$comptime45["value"];
    if (valueJson$comptime49 === undefined) {
      return;
    }
    let value$comptime51;
    value$comptime51 = typeof valueJson$comptime49 === "number" ? valueJson$comptime49 | 0 : undefined;
    if (value$comptime51 !== undefined) {
      return {
        TAG: "Ok",
        _0: value$comptime51
      };
    } else {
      return;
    }
  }
  if ("Error" !== match) {
    return;
  }
  let valueJson$comptime52 = json$comptime45["value"];
  if (valueJson$comptime52 === undefined) {
    return;
  }
  let value$comptime54;
  value$comptime54 = typeof valueJson$comptime52 === "string" ? valueJson$comptime52 : undefined;
  if (value$comptime54 !== undefined) {
    return {
      TAG: "Error",
      _0: value$comptime54
    };
  }
}

let jsonAda = {
  name: "Ada",
  age: 42,
  active: true
};

let jsonPair = [
  "Ada",
  42
];

let jsonColor = "Green";

let jsonShape = {
  tag: "Rect",
  value: [
    3,
    4
  ]
};

let jsonNumbers = [
  1,
  2,
  3
];

let jsonScore = {
  tag: "Ok",
  value: 7
};

let decodedAda = decodeUser(jsonAda);

let decodedPair = decodePair(jsonPair);

let decodedColor = decodeColor(jsonColor);

let decodedShape = decodeShape(jsonShape);

let decodedNumbers = decodeInts(jsonNumbers);

let decodedScore = decodeResult(jsonScore);

console.log(decodedAda);

console.log(decodedPair);

console.log(decodedColor);

console.log(decodedShape);

console.log(decodedNumbers);

console.log(decodedScore);

let ada = {
  name: "Ada",
  age: 42,
  active: true
};

let agePair = [
  "Ada",
  42
];

let favoriteColor = "Green";

let sampleShape = {
  TAG: "Rect",
  _0: 3,
  _1: 4
};

let numbers = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

let score = {
  TAG: "Ok",
  _0: 7
};

export {
  decodeUser,
  decodePair,
  decodeColor,
  decodeShape,
  decodeInts,
  decodeResult,
  ada,
  agePair,
  favoriteColor,
  sampleShape,
  numbers,
  score,
  jsonAda,
  jsonPair,
  jsonColor,
  jsonShape,
  jsonNumbers,
  jsonScore,
  decodedAda,
  decodedPair,
  decodedColor,
  decodedShape,
  decodedNumbers,
  decodedScore,
}
/* decodedAda Not a pure module */
