// Generated by ReScript, PLEASE EDIT WITH CARE


function encodeUser(value) {
  return {
    name: value.name,
    age: value.age,
    active: value.active
  };
}

function decodeUser(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let match = json["name"];
  let match$1 = typeof match === "string" ? match : undefined;
  let match$2 = json["age"];
  let match$3 = typeof match$2 === "number" ? match$2 | 0 : undefined;
  let match$4 = json["active"];
  let match$5 = typeof match$4 === "boolean" ? match$4 : undefined;
  if (match$1 !== undefined && match$3 !== undefined && match$5 !== undefined) {
    return {
      name: match$1,
      age: match$3,
      active: match$5
    };
  }
}

let ada = {
  name: "Ada",
  age: 42,
  active: true
};

let encodedAda = encodeUser(ada);

let decodedAda = decodeUser(encodedAda);

console.log(encodedAda);

console.log(decodedAda);

export {
  encodeUser,
  decodeUser,
  ada,
  encodedAda,
  decodedAda,
}
/* encodedAda Not a pure module */
