// Generated by ReScript, PLEASE EDIT WITH CARE


function encodeUser(value$comptime1) {
  return Object.fromEntries([
    [
      "name",
      value$comptime1.name
    ],
    [
      "age",
      value$comptime1.age
    ],
    [
      "active",
      value$comptime1.active
    ]
  ]);
}

function decodeUser(json$comptime2) {
  if (typeof json$comptime2 !== "object" || json$comptime2 === null || Array.isArray(json$comptime2)) {
    return;
  }
  let match = json$comptime2["name"];
  let value$comptime5 = typeof match === "string" ? match : undefined;
  if (value$comptime5 === undefined) {
    return;
  }
  let match$1 = json$comptime2["age"];
  let value$comptime7 = typeof match$1 === "number" ? match$1 | 0 : undefined;
  if (value$comptime7 === undefined) {
    return;
  }
  let match$2 = json$comptime2["active"];
  let value$comptime9 = typeof match$2 === "boolean" ? match$2 : undefined;
  if (value$comptime9 !== undefined) {
    return {
      name: value$comptime5,
      age: value$comptime7,
      active: value$comptime9
    };
  }
}

function copyUser(value$comptime10) {
  return {
    name: value$comptime10.name,
    age: value$comptime10.age,
    active: value$comptime10.active
  };
}

function encodeAnimal(value$comptime11) {
  return Object.fromEntries([
    [
      "species",
      value$comptime11.species
    ],
    [
      "age",
      value$comptime11.age
    ],
    [
      "wild",
      value$comptime11.wild
    ]
  ]);
}

function decodeAnimal(json$comptime12) {
  if (typeof json$comptime12 !== "object" || json$comptime12 === null || Array.isArray(json$comptime12)) {
    return;
  }
  let match = json$comptime12["species"];
  let value$comptime15 = typeof match === "string" ? match : undefined;
  if (value$comptime15 === undefined) {
    return;
  }
  let match$1 = json$comptime12["age"];
  let value$comptime17 = typeof match$1 === "number" ? match$1 | 0 : undefined;
  if (value$comptime17 === undefined) {
    return;
  }
  let match$2 = json$comptime12["wild"];
  let value$comptime19 = typeof match$2 === "boolean" ? match$2 : undefined;
  if (value$comptime19 !== undefined) {
    return {
      species: value$comptime15,
      age: value$comptime17,
      wild: value$comptime19
    };
  }
}

function copyAnimal(value$comptime20) {
  return {
    species: value$comptime20.species,
    age: value$comptime20.age,
    wild: value$comptime20.wild
  };
}

let greeting = "comptime";

let ada = {
  name: "Ada",
  age: 42,
  active: true
};

let encodedAda = encodeUser(ada);

let decodedAda = decodeUser(encodedAda);

let copiedAda = copyUser(ada);

let fox = {
  species: "Fox",
  age: 5,
  wild: true
};

let encodedFox = encodeAnimal(fox);

let decodedFox = decodeAnimal(encodedFox);

let copiedFox = copyAnimal(fox);

console.log(3);

console.log(greeting);

console.log(encodedAda);

console.log(decodedAda);

console.log(copiedAda);

console.log(encodedFox);

console.log(decodedFox);

console.log(copiedFox);

let three = 3;

export {
  encodeUser,
  decodeUser,
  copyUser,
  encodeAnimal,
  decodeAnimal,
  copyAnimal,
  three,
  greeting,
  ada,
  encodedAda,
  decodedAda,
  copiedAda,
  fox,
  encodedFox,
  decodedFox,
  copiedFox,
}
/* encodedAda Not a pure module */
