// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

function encodeUser(value$comptime1) {
  return Object.fromEntries([
    [
      "name",
      value$comptime1.name
    ],
    [
      "age",
      value$comptime1.age
    ],
    [
      "active",
      value$comptime1.active
    ]
  ]);
}

function decodeUser(json$comptime2) {
  if (typeof json$comptime2 !== "object" || json$comptime2 === null || Array.isArray(json$comptime2)) {
    return;
  }
  let valueJson$comptime4 = json$comptime2["name"];
  if (valueJson$comptime4 === undefined) {
    return;
  }
  let value$comptime6;
  value$comptime6 = typeof valueJson$comptime4 === "string" ? valueJson$comptime4 : undefined;
  if (value$comptime6 === undefined) {
    return;
  }
  let valueJson$comptime7 = json$comptime2["age"];
  if (valueJson$comptime7 === undefined) {
    return;
  }
  let value$comptime9;
  value$comptime9 = typeof valueJson$comptime7 === "number" ? valueJson$comptime7 | 0 : undefined;
  if (value$comptime9 === undefined) {
    return;
  }
  let valueJson$comptime10 = json$comptime2["active"];
  if (valueJson$comptime10 === undefined) {
    return;
  }
  let value$comptime12;
  value$comptime12 = typeof valueJson$comptime10 === "boolean" ? valueJson$comptime10 : undefined;
  if (value$comptime12 !== undefined) {
    return {
      name: value$comptime6,
      age: value$comptime9,
      active: value$comptime12
    };
  }
}

function copyUser(value$comptime13) {
  return {
    name: value$comptime13.name,
    age: value$comptime13.age,
    active: value$comptime13.active
  };
}

function encodeAnimal(value$comptime14) {
  return Object.fromEntries([
    [
      "species",
      value$comptime14.species
    ],
    [
      "age",
      value$comptime14.age
    ],
    [
      "wild",
      value$comptime14.wild
    ]
  ]);
}

function decodeAnimal(json$comptime15) {
  if (typeof json$comptime15 !== "object" || json$comptime15 === null || Array.isArray(json$comptime15)) {
    return;
  }
  let valueJson$comptime17 = json$comptime15["species"];
  if (valueJson$comptime17 === undefined) {
    return;
  }
  let value$comptime19;
  value$comptime19 = typeof valueJson$comptime17 === "string" ? valueJson$comptime17 : undefined;
  if (value$comptime19 === undefined) {
    return;
  }
  let valueJson$comptime20 = json$comptime15["age"];
  if (valueJson$comptime20 === undefined) {
    return;
  }
  let value$comptime22;
  value$comptime22 = typeof valueJson$comptime20 === "number" ? valueJson$comptime20 | 0 : undefined;
  if (value$comptime22 === undefined) {
    return;
  }
  let valueJson$comptime23 = json$comptime15["wild"];
  if (valueJson$comptime23 === undefined) {
    return;
  }
  let value$comptime25;
  value$comptime25 = typeof valueJson$comptime23 === "boolean" ? valueJson$comptime23 : undefined;
  if (value$comptime25 !== undefined) {
    return {
      species: value$comptime19,
      age: value$comptime22,
      wild: value$comptime25
    };
  }
}

function copyAnimal(value$comptime26) {
  return {
    species: value$comptime26.species,
    age: value$comptime26.age,
    wild: value$comptime26.wild
  };
}

function encodePair(value$comptime27) {
  return [
    value$comptime27[0],
    value$comptime27[1]
  ];
}

function decodePair(json$comptime28) {
  if (!Array.isArray(json$comptime28)) {
    return;
  }
  let valueJson$comptime30 = json$comptime28[0];
  if (valueJson$comptime30 === undefined) {
    return;
  }
  let value$comptime32;
  value$comptime32 = typeof valueJson$comptime30 === "string" ? valueJson$comptime30 : undefined;
  if (value$comptime32 === undefined) {
    return;
  }
  let valueJson$comptime33 = json$comptime28[1];
  if (valueJson$comptime33 === undefined) {
    return;
  }
  let value$comptime35;
  value$comptime35 = typeof valueJson$comptime33 === "number" ? valueJson$comptime33 | 0 : undefined;
  if (value$comptime35 !== undefined) {
    return [
      value$comptime32,
      value$comptime35
    ];
  }
}

function copyPair(value$comptime36) {
  return [
    value$comptime36[0],
    value$comptime36[1]
  ];
}

function encodeColor(value$comptime37) {
  let match;
  switch (value$comptime37) {
    case "Red" :
      match = Primitive_option.some(undefined);
      break;
    case "Green" :
    case "Blue" :
      match = undefined;
      break;
  }
  if (match !== undefined) {
    return "Red";
  }
  let match$1;
  switch (value$comptime37) {
    case "Green" :
      match$1 = Primitive_option.some(undefined);
      break;
    case "Red" :
    case "Blue" :
      match$1 = undefined;
      break;
  }
  if (match$1 !== undefined) {
    return "Green";
  }
  let match$2;
  switch (value$comptime37) {
    case "Red" :
    case "Green" :
      match$2 = undefined;
      break;
    case "Blue" :
      match$2 = Primitive_option.some(undefined);
      break;
  }
  if (match$2 !== undefined) {
    return "Blue";
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function decodeColor(json$comptime38) {
  if (typeof json$comptime38 === "string") {
    if ("Red" === json$comptime38) {
      return "Red";
    } else if ("Green" === json$comptime38) {
      return "Green";
    } else if ("Blue" === json$comptime38) {
      return "Blue";
    } else {
      return;
    }
  }
}

function copyColor(value$comptime42) {
  let match;
  switch (value$comptime42) {
    case "Red" :
      match = Primitive_option.some(undefined);
      break;
    case "Green" :
    case "Blue" :
      match = undefined;
      break;
  }
  if (match !== undefined) {
    return "Red";
  }
  let match$1;
  switch (value$comptime42) {
    case "Green" :
      match$1 = Primitive_option.some(undefined);
      break;
    case "Red" :
    case "Blue" :
      match$1 = undefined;
      break;
  }
  if (match$1 !== undefined) {
    return "Green";
  }
  let match$2;
  switch (value$comptime42) {
    case "Red" :
    case "Green" :
      match$2 = undefined;
      break;
    case "Blue" :
      match$2 = Primitive_option.some(undefined);
      break;
  }
  if (match$2 !== undefined) {
    return "Blue";
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

let allColors = [
  "Red",
  "Green",
  "Blue"
];

function encodeUserFieldValue(value$comptime43) {
  let payload$comptime44;
  switch (value$comptime43.TAG) {
    case "Name" :
      payload$comptime44 = value$comptime43._0;
      break;
    case "Age" :
    case "Active" :
      payload$comptime44 = undefined;
      break;
  }
  if (payload$comptime44 !== undefined) {
    return {
      tag: "Name",
      value: payload$comptime44
    };
  }
  let payload$comptime45;
  switch (value$comptime43.TAG) {
    case "Age" :
      payload$comptime45 = value$comptime43._0;
      break;
    case "Name" :
    case "Active" :
      payload$comptime45 = undefined;
      break;
  }
  if (payload$comptime45 !== undefined) {
    return {
      tag: "Age",
      value: payload$comptime45
    };
  }
  let payload$comptime46;
  switch (value$comptime43.TAG) {
    case "Name" :
    case "Age" :
      payload$comptime46 = undefined;
      break;
    case "Active" :
      payload$comptime46 = value$comptime43._0;
      break;
  }
  if (payload$comptime46 !== undefined) {
    return {
      tag: "Active",
      value: payload$comptime46
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function decodeUserFieldValue(json$comptime47) {
  if (typeof json$comptime47 !== "object" || json$comptime47 === null || Array.isArray(json$comptime47)) {
    return;
  }
  let match = json$comptime47["tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if ("Name" === match) {
    let valueJson$comptime51 = json$comptime47["value"];
    if (valueJson$comptime51 === undefined) {
      return;
    }
    let value$comptime53;
    value$comptime53 = typeof valueJson$comptime51 === "string" ? valueJson$comptime51 : undefined;
    if (value$comptime53 !== undefined) {
      return {
        TAG: "Name",
        _0: value$comptime53
      };
    } else {
      return;
    }
  }
  if ("Age" === match) {
    let valueJson$comptime54 = json$comptime47["value"];
    if (valueJson$comptime54 === undefined) {
      return;
    }
    let value$comptime56;
    value$comptime56 = typeof valueJson$comptime54 === "number" ? valueJson$comptime54 | 0 : undefined;
    if (value$comptime56 !== undefined) {
      return {
        TAG: "Age",
        _0: value$comptime56
      };
    } else {
      return;
    }
  }
  if ("Active" !== match) {
    return;
  }
  let valueJson$comptime57 = json$comptime47["value"];
  if (valueJson$comptime57 === undefined) {
    return;
  }
  let value$comptime59;
  value$comptime59 = typeof valueJson$comptime57 === "boolean" ? valueJson$comptime57 : undefined;
  if (value$comptime59 !== undefined) {
    return {
      TAG: "Active",
      _0: value$comptime59
    };
  }
}

function copyUserFieldValue(value$comptime60) {
  let payload$comptime61;
  switch (value$comptime60.TAG) {
    case "Name" :
      payload$comptime61 = value$comptime60._0;
      break;
    case "Age" :
    case "Active" :
      payload$comptime61 = undefined;
      break;
  }
  if (payload$comptime61 !== undefined) {
    return {
      TAG: "Name",
      _0: payload$comptime61
    };
  }
  let payload$comptime62;
  switch (value$comptime60.TAG) {
    case "Age" :
      payload$comptime62 = value$comptime60._0;
      break;
    case "Name" :
    case "Active" :
      payload$comptime62 = undefined;
      break;
  }
  if (payload$comptime62 !== undefined) {
    return {
      TAG: "Age",
      _0: payload$comptime62
    };
  }
  let payload$comptime63;
  switch (value$comptime60.TAG) {
    case "Name" :
    case "Age" :
      payload$comptime63 = undefined;
      break;
    case "Active" :
      payload$comptime63 = value$comptime60._0;
      break;
  }
  if (payload$comptime63 !== undefined) {
    return {
      TAG: "Active",
      _0: payload$comptime63
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function encodeShape(value$comptime64) {
  let match;
  match = typeof value$comptime64 !== "object" ? Primitive_option.some(undefined) : undefined;
  if (match !== undefined) {
    return {
      tag: "Point"
    };
  }
  let payload$comptime65;
  payload$comptime65 = typeof value$comptime64 !== "object" || value$comptime64.TAG !== "Circle" ? undefined : value$comptime64._0;
  if (payload$comptime65 !== undefined) {
    return {
      tag: "Circle",
      value: payload$comptime65
    };
  }
  let payload$comptime66;
  payload$comptime66 = typeof value$comptime64 !== "object" || value$comptime64.TAG === "Circle" ? undefined : [
      value$comptime64._0,
      value$comptime64._1
    ];
  if (payload$comptime66 !== undefined) {
    return {
      tag: "Rect",
      value: [
        payload$comptime66[0],
        payload$comptime66[1]
      ]
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function decodeShape(json$comptime67) {
  if (typeof json$comptime67 !== "object" || json$comptime67 === null || Array.isArray(json$comptime67)) {
    return;
  }
  let match = json$comptime67["tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if ("Point" === match) {
    return "Point";
  }
  if ("Circle" === match) {
    let valueJson$comptime71 = json$comptime67["value"];
    if (valueJson$comptime71 === undefined) {
      return;
    }
    let value$comptime73;
    value$comptime73 = typeof valueJson$comptime71 === "number" ? valueJson$comptime71 : undefined;
    if (value$comptime73 !== undefined) {
      return {
        TAG: "Circle",
        _0: value$comptime73
      };
    } else {
      return;
    }
  }
  if ("Rect" !== match) {
    return;
  }
  let valueJson$comptime74 = json$comptime67["value"];
  if (valueJson$comptime74 === undefined) {
    return;
  }
  let value$comptime82;
  if (Array.isArray(valueJson$comptime74)) {
    let valueJson$comptime76 = valueJson$comptime74[0];
    if (valueJson$comptime76 !== undefined) {
      let value$comptime78;
      value$comptime78 = typeof valueJson$comptime76 === "number" ? valueJson$comptime76 : undefined;
      if (value$comptime78 !== undefined) {
        let valueJson$comptime79 = valueJson$comptime74[1];
        if (valueJson$comptime79 !== undefined) {
          let value$comptime81;
          value$comptime81 = typeof valueJson$comptime79 === "number" ? valueJson$comptime79 : undefined;
          value$comptime82 = value$comptime81 !== undefined ? [
              value$comptime78,
              value$comptime81
            ] : undefined;
        } else {
          value$comptime82 = undefined;
        }
      } else {
        value$comptime82 = undefined;
      }
    } else {
      value$comptime82 = undefined;
    }
  } else {
    value$comptime82 = undefined;
  }
  if (value$comptime82 !== undefined) {
    return {
      TAG: "Rect",
      _0: value$comptime82[0],
      _1: value$comptime82[1]
    };
  }
}

function copyShape(value$comptime83) {
  let match;
  match = typeof value$comptime83 !== "object" ? Primitive_option.some(undefined) : undefined;
  if (match !== undefined) {
    return "Point";
  }
  let payload$comptime84;
  payload$comptime84 = typeof value$comptime83 !== "object" || value$comptime83.TAG !== "Circle" ? undefined : value$comptime83._0;
  if (payload$comptime84 !== undefined) {
    return {
      TAG: "Circle",
      _0: payload$comptime84
    };
  }
  let payload$comptime85;
  payload$comptime85 = typeof value$comptime83 !== "object" || value$comptime83.TAG === "Circle" ? undefined : [
      value$comptime83._0,
      value$comptime83._1
    ];
  if (payload$comptime85 !== undefined) {
    return {
      TAG: "Rect",
      _0: payload$comptime85[0],
      _1: payload$comptime85[1]
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function encodeInts(value$comptime86) {
  return Stdlib_List.toArray(value$comptime86).map(arg$comptime0 => (arg$comptime0));
}

function decodeInts(json$comptime87) {
  if (Array.isArray(json$comptime87)) {
    return Stdlib_Array.reduceRight(json$comptime87, /* [] */0, (arg$comptime0, arg$comptime1) => {
      let match;
      match = typeof arg$comptime1 === "number" ? arg$comptime1 | 0 : undefined;
      if (match !== undefined && arg$comptime0 !== undefined) {
        return {
          hd: match,
          tl: arg$comptime0
        };
      }
    });
  }
}

function copyInts(value$comptime92) {
  return Stdlib_List.fromArray(Stdlib_List.toArray(value$comptime92).map(arg$comptime0 => arg$comptime0));
}

function encodeResult(value$comptime93) {
  let payload$comptime94;
  payload$comptime94 = value$comptime93.TAG === "Ok" ? value$comptime93._0 : undefined;
  if (payload$comptime94 !== undefined) {
    return {
      tag: "Ok",
      value: payload$comptime94
    };
  }
  let payload$comptime95;
  payload$comptime95 = value$comptime93.TAG === "Ok" ? undefined : value$comptime93._0;
  if (payload$comptime95 !== undefined) {
    return {
      tag: "Error",
      value: payload$comptime95
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

function decodeResult(json$comptime96) {
  if (typeof json$comptime96 !== "object" || json$comptime96 === null || Array.isArray(json$comptime96)) {
    return;
  }
  let match = json$comptime96["tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if ("Ok" === match) {
    let valueJson$comptime100 = json$comptime96["value"];
    if (valueJson$comptime100 === undefined) {
      return;
    }
    let value$comptime102;
    value$comptime102 = typeof valueJson$comptime100 === "number" ? valueJson$comptime100 | 0 : undefined;
    if (value$comptime102 !== undefined) {
      return {
        TAG: "Ok",
        _0: value$comptime102
      };
    } else {
      return;
    }
  }
  if ("Error" !== match) {
    return;
  }
  let valueJson$comptime103 = json$comptime96["value"];
  if (valueJson$comptime103 === undefined) {
    return;
  }
  let value$comptime105;
  value$comptime105 = typeof valueJson$comptime103 === "string" ? valueJson$comptime103 : undefined;
  if (value$comptime105 !== undefined) {
    return {
      TAG: "Error",
      _0: value$comptime105
    };
  }
}

function copyResult(value$comptime106) {
  let payload$comptime107;
  payload$comptime107 = value$comptime106.TAG === "Ok" ? value$comptime106._0 : undefined;
  if (payload$comptime107 !== undefined) {
    return {
      TAG: "Ok",
      _0: payload$comptime107
    };
  }
  let payload$comptime108;
  payload$comptime108 = value$comptime106.TAG === "Ok" ? undefined : value$comptime106._0;
  if (payload$comptime108 !== undefined) {
    return {
      TAG: "Error",
      _0: payload$comptime108
    };
  } else {
    return Stdlib_JsError.throwWithMessage("variant value did not match any constructor");
  }
}

let greeting = "comptime";

let ada = {
  name: "Ada",
  age: 42,
  active: true
};

let fox = {
  species: "Fox",
  age: 5,
  wild: true
};

let agePair = [
  "Ada",
  42
];

let userNameField = {
  TAG: "Name",
  _0: "Ada"
};

let userAgeField = {
  TAG: "Age",
  _0: 42
};

let userActiveField = {
  TAG: "Active",
  _0: true
};

let sampleShape = {
  TAG: "Rect",
  _0: 3,
  _1: 4
};

let numbers = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

let score = {
  TAG: "Ok",
  _0: 7
};

let encodedAda = encodeUser(ada);

let encodedFox = encodeAnimal(fox);

let encodedPair = encodePair(agePair);

let encodedColor = encodeColor("Green");

let encodedUserAgeField = encodeUserFieldValue(userAgeField);

let encodedShape = encodeShape(sampleShape);

let encodedNumbers = encodeInts(numbers);

let encodedScore = encodeResult(score);

let copiedAda = copyUser(ada);

console.log(3);

console.log(greeting);

console.log(encodedAda);

console.log(decodeUser(encodedAda));

console.log(copiedAda);

console.log(encodedFox);

console.log(decodeAnimal(encodedFox));

console.log(copyAnimal(fox));

console.log(encodedPair);

console.log(decodePair(encodedPair));

console.log(copyPair(agePair));

console.log(encodedColor);

console.log(decodeColor(encodedColor));

console.log(copyColor("Green"));

console.log(allColors);

console.log(userNameField);

console.log(userAgeField);

console.log(userActiveField);

console.log(encodedUserAgeField);

console.log(decodeUserFieldValue(encodedUserAgeField));

console.log(copyUserFieldValue(userActiveField));

console.log(encodedShape);

console.log(decodeShape(encodedShape));

console.log(copyShape(sampleShape));

console.log(encodedNumbers);

console.log(decodeInts(encodedNumbers));

console.log(copyInts(numbers));

console.log(encodedScore);

console.log(decodeResult(encodedScore));

console.log(copyResult(score));

let three = 3;

let favoriteColor = "Green";

export {
  encodeUser,
  decodeUser,
  copyUser,
  encodeAnimal,
  decodeAnimal,
  copyAnimal,
  encodePair,
  decodePair,
  copyPair,
  encodeColor,
  decodeColor,
  copyColor,
  allColors,
  encodeUserFieldValue,
  decodeUserFieldValue,
  copyUserFieldValue,
  encodeShape,
  decodeShape,
  copyShape,
  encodeInts,
  decodeInts,
  copyInts,
  encodeResult,
  decodeResult,
  copyResult,
  three,
  greeting,
  ada,
  fox,
  agePair,
  favoriteColor,
  userNameField,
  userAgeField,
  userActiveField,
  sampleShape,
  numbers,
  score,
  encodedAda,
  encodedFox,
  encodedPair,
  encodedColor,
  encodedUserAgeField,
  encodedShape,
  encodedNumbers,
  encodedScore,
  copiedAda,
}
/* encodedAda Not a pure module */
