// Generated by ReScript, PLEASE EDIT WITH CARE


let emptyOptionalValueR0 = {
  name: undefined,
  age: undefined
};

let fullOptionalValueR0 = {
  name: "Ada",
  age: 42
};

let emptyOptionalFieldR0 = {};

let fullOptionalFieldR0 = {
  name: "Ada",
  age: 42
};

console.log(emptyOptionalValueR0);

console.log(fullOptionalValueR0);

console.log(emptyOptionalFieldR0);

console.log(fullOptionalFieldR0);

export {
  emptyOptionalValueR0,
  fullOptionalValueR0,
  emptyOptionalFieldR0,
  fullOptionalFieldR0,
}
/*  Not a pure module */
