// Generated by ReScript, PLEASE EDIT WITH CARE


let personR0 = {
  name: "Ada"
};

console.log(personR0);

let personR1 = {
  name: "Idris",
  age: 19
};

export {
  personR0,
  personR1,
}
/*  Not a pure module */
