// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";

function encodeTree(value$comptime1) {
  let encodeByType$rec$comptime2 = value$comptime3 => {
    let encodeByType$rec$comptime4 = value$comptime5 => (value$comptime5.map(encodeByType$rec$comptime2));
    return Object.fromEntries([
      [
        "value",
        value$comptime3.value
      ],
      [
        "children",
        encodeByType$rec$comptime4(value$comptime3.children)
      ]
    ]);
  };
  return encodeByType$rec$comptime2(value$comptime1);
}

function decodeTree(json$comptime6) {
  let decodeByType$rec$comptime7 = json$comptime8 => {
    if (typeof json$comptime8 !== "object" || json$comptime8 === null || Array.isArray(json$comptime8)) {
      return;
    }
    let valueJson$comptime10 = json$comptime8["value"];
    if (valueJson$comptime10 === undefined) {
      return;
    }
    let value$comptime12;
    value$comptime12 = typeof valueJson$comptime10 === "string" ? valueJson$comptime10 : undefined;
    if (value$comptime12 === undefined) {
      return;
    }
    let valueJson$comptime13 = json$comptime8["children"];
    if (valueJson$comptime13 === undefined) {
      return;
    }
    let decodeByType$rec$comptime14 = json$comptime15 => {
      if (!Array.isArray(json$comptime15)) {
        return;
      }
      let values$comptime19 = Stdlib_Array.reduceRight(json$comptime15, /* [] */0, (arg$comptime0, arg$comptime1) => {
        let match = decodeByType$rec$comptime7(arg$comptime1);
        if (match !== undefined && arg$comptime0 !== undefined) {
          return {
            hd: match,
            tl: arg$comptime0
          };
        }
      });
      if (values$comptime19 !== undefined) {
        return Stdlib_List.toArray(values$comptime19);
      }
    };
    let value$comptime20 = decodeByType$rec$comptime14(valueJson$comptime13);
    if (value$comptime20 !== undefined) {
      return {
        value: value$comptime12,
        children: value$comptime20
      };
    }
  };
  return decodeByType$rec$comptime7(json$comptime6);
}

let sampleTree_children = [
  {
    value: "left",
    children: []
  },
  {
    value: "right",
    children: [{
        value: "leaf",
        children: []
      }]
  }
];

let sampleTree = {
  value: "root",
  children: sampleTree_children
};

let jsonTree = {
  value: "root",
  children: [
    {
      value: "left",
      children: []
    },
    {
      value: "right",
      children: [{
          value: "leaf",
          children: []
        }]
    }
  ]
};

let encodedTree = encodeTree(sampleTree);

let decodedTree = decodeTree(jsonTree);

console.log(encodedTree);

console.log(decodedTree);

export {
  encodeTree,
  decodeTree,
  sampleTree,
  jsonTree,
  encodedTree,
  decodedTree,
}
/* encodedTree Not a pure module */
