// Generated by ReScript, PLEASE EDIT WITH CARE


let userNameField = {
  TAG: "Name",
  _0: "Ada"
};

let userAgeField = {
  TAG: "Age",
  _0: 42
};

let userActiveField = {
  TAG: "Active",
  _0: true
};

function fieldLabel(field) {
  switch (field.TAG) {
    case "Name" :
      return "Name";
    case "Age" :
      return "Age";
    case "Active" :
      return "Active";
  }
}

console.log(userNameField);

console.log(userAgeField);

console.log(userActiveField);

console.log(fieldLabel(userAgeField));

export {
  userNameField,
  userAgeField,
  userActiveField,
  fieldLabel,
}
/*  Not a pure module */
